{
 "title": "5003project_legacy_blockchain_market_mainDashboard",
 "description": "1",
 "time": { "from": "2024-12-31T16:00:00.000Z", "to": "2025-04-30T16:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "prediction_target",
    "query": {
     "query": "SELECT DISTINCT target_symbol FROM predictions;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "model trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n    time,\r\n    MAX(actual_price) AS actual_price,\r\n    MAX(CASE WHEN series_name = 'Linear Regression' THEN predicted_price END) AS linear_regression,\r\n    MAX(CASE WHEN series_name = 'Decision Tree Regressor' THEN predicted_price END) AS decision_tree,\r\n    MAX(CASE WHEN series_name = 'Random Forest Regressor' THEN predicted_price END) AS random_forest,\r\n    MAX(CASE WHEN series_name = 'GBT Regressor' THEN predicted_price END) AS gbt_regressor\r\nFROM public.ml_btc_predictions_timeseries\r\nWHERE $__timeFilter(time)\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "prediction result",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  prediction_time AS \"time\",\r\n  CASE\r\n    WHEN is_up_predicted = TRUE THEN confidence_score * 100\r\n    ELSE (1.0 - confidence_score) * 100\r\n  END AS value\r\nFROM predictions\r\nWHERE $__timeFilter(prediction_time)\r\n  AND target_symbol = '$prediction_target'\r\nORDER BY prediction_time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "ML models",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n    model_name,\r\n    ROUND(rmse::numeric, 2) AS rmse,\r\n    ROUND(mae::numeric, 2) AS mae,\r\n    ROUND(r2::numeric, 4) AS r2,\r\n    train_rows,\r\n    test_rows,\r\n    feature_count,\r\n    cv_method,\r\n    best_params\r\nFROM public.ml_btc_model_metrics\r\nORDER BY rmse ASC;"
    }
   ]
  },
  {
   "title": "US Stock Most Volatile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM us_stock_summary\r\nWHERE metric_type = 'price_range'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM us_stock_summary\r\n    WHERE metric_type = 'price_range'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "prediction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n    event_time,\r\n    actual_price,\r\n    predicted_price,\r\n    error_usd,\r\n    accuracy_pct\r\nFROM public.ml_btc_predictions\r\nWHERE event_time IS NOT NULL\r\nORDER BY event_time ASC;"
    }
   ]
  },
  {
   "title": "HOW MANY STOCK or CYPTO?",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  type,\r\n  count(DISTINCT symbol) AS \"assets count\"\r\nFROM realtime_prices\r\nWHERE type IN ('hk_stock', 'us_stock', 'crypto', 'index', 'war_oil') -- 🌟 淨係睇呢幾類\r\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Crypto Most Volatile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM crypto_summary\r\nWHERE metric_type = 'price_range'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM crypto_summary\r\n    WHERE metric_type = 'price_range'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "TX vs BTCprice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  \"time\",\r\n  tx_count,\r\n  btc_avg_price\r\nFROM real_time_fusion_dashboard\r\nWHERE $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "Crypto Top Momentum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM crypto_summary\r\nWHERE metric_type = 'momentum'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM crypto_summary\r\n    WHERE metric_type = 'momentum'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "btcBC_txCount & 7dayAVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  time_bucket AS \"time\",\r\n  tx_count,\r\n  tx_count_7d_avg\r\nFROM live_blockchain_metrics\r\nWHERE $__timeFilter(time_bucket)\r\nORDER BY time_bucket ASC;"
    }
   ]
  },
  {
   "title": "Crypto Live",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE \r\n  -- 限制只抓過去 3 天的資料，避免掃描全表\r\n  window_start >= NOW() - INTERVAL '3 days'\r\n  AND $__timeFilter(window_start) \r\nORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "SELECT   symbol,   MAX(CASE WHEN metric_type = 'momentum' THEN metric_value END) AS momentum,   MAX(CASE WHEN metric_type = 'price_range' THEN metric_value END) AS price_range FROM crypto_summary WHERE summary_time = (   SELECT MAX(summary_time)   FROM crypto_summary ) GROUP BY symbol ORDER BY momentum DESC;",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol,\r\n  MAX(CASE WHEN metric_type = 'momentum' THEN metric_value END) AS momentum,\r\n  MAX(CASE WHEN metric_type = 'price_range' THEN metric_value END) AS price_range\r\nFROM crypto_summary\r\nWHERE summary_time = (\r\n  SELECT MAX(summary_time)\r\n  FROM crypto_summary\r\n)\r\nGROUP BY symbol\r\nORDER BY momentum DESC;"
    }
   ]
  },
  {
   "title": "BTC latest value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  symbol AS metric,\r\n  avg_price AS value\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND symbol = 'BTCUSDT'\r\n  ORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "US_stock",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  -- 🌟 核心魔法：只過濾美股同油股\r\n  AND type IN ('us_stock', 'war_oil') \r\nORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "actual price vs prediction confidence",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  symbol || ' (Actual)' AS metric,\r\n  avg_price AS value\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND symbol = '$prediction_target'\r\nORDER BY window_start ASC;"
    },
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  prediction_time AS \"time\",\r\n  target_symbol || ' (AI Confidence %)' AS metric,\r\n  (confidence_score * 100) AS value\r\nFROM predictions\r\nWHERE $__timeFilter(prediction_time)\r\n  AND target_symbol = '$prediction_target'\r\nORDER BY prediction_time ASC;"
    }
   ]
  },
  {
   "title": "Asia HK Stocks & Indices live",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND type IN ('hk_stock', 'index')\r\n  AND window_start >= '2026-03-31'\r\n  AND window_start < '2026-04-07'\r\nORDER BY window_start ASC;"
    }
   ]
  }
 ]
}