{
 "title": "New dashboard",
 "description": "1",
 "time": { "from": "2026-03-31T16:50:25.769Z", "to": "2026-03-31T16:50:58.387Z" },
 "templating": {
  "list": [
   {
    "name": "prediction_target",
    "query": {
     "query": "SELECT DISTINCT target_symbol FROM predictions;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  \"time\",\r\n  actual_price,\r\n  predicted_price\r\nFROM ml_btc_predictions\r\nWHERE $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "prediction result",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  prediction_time AS \"time\",\r\n  CASE\r\n    WHEN is_up_predicted = TRUE THEN confidence_score * 100\r\n    ELSE (1.0 - confidence_score) * 100\r\n  END AS value\r\nFROM predictions\r\nWHERE $__timeFilter(prediction_time)\r\n  AND target_symbol = '$prediction_target'\r\nORDER BY prediction_time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "TX vs BTCprice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  \"time\",\r\n  tx_count,\r\n  btc_avg_price\r\nFROM real_time_fusion_dashboard\r\nWHERE $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "actual price vs prediction confidence",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  symbol || ' (Actual)' AS metric,\r\n  avg_price AS value\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND symbol = '$prediction_target'\r\nORDER BY window_start ASC;"
    },
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  prediction_time AS \"time\",\r\n  target_symbol || ' (AI Confidence %)' AS metric,\r\n  (confidence_score * 100) AS value\r\nFROM predictions\r\nWHERE $__timeFilter(prediction_time)\r\n  AND target_symbol = '$prediction_target'\r\nORDER BY prediction_time ASC;"
    }
   ]
  },
  {
   "title": "btcBC_txCount & 7dayAVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  time_bucket AS \"time\",\r\n  tx_count,\r\n  tx_count_7d_avg\r\nFROM live_blockchain_metrics\r\nWHERE $__timeFilter(time_bucket)\r\nORDER BY time_bucket ASC;"
    }
   ]
  },
  {
   "title": "SELECT   symbol,   MAX(CASE WHEN metric_type = 'momentum' THEN metric_value END) AS momentum,   MAX(CASE WHEN metric_type = 'price_range' THEN metric_value END) AS price_range FROM crypto_summary WHERE summary_time = (   SELECT MAX(summary_time)   FROM crypto_summary ) GROUP BY symbol ORDER BY momentum DESC;",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol,\r\n  MAX(CASE WHEN metric_type = 'momentum' THEN metric_value END) AS momentum,\r\n  MAX(CASE WHEN metric_type = 'price_range' THEN metric_value END) AS price_range\r\nFROM crypto_summary\r\nWHERE summary_time = (\r\n  SELECT MAX(summary_time)\r\n  FROM crypto_summary\r\n)\r\nGROUP BY symbol\r\nORDER BY momentum DESC;"
    }
   ]
  },
  {
   "title": "Crypto Live",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND type = 'crypto' -- 🌟 核心魔法：只允許加密貨幣進入這張圖\r\nORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "Crypto Top Momentum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM crypto_summary\r\nWHERE metric_type = 'momentum'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM crypto_summary\r\n    WHERE metric_type = 'momentum'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Crypto Most Volatile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM crypto_summary\r\nWHERE metric_type = 'price_range'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM crypto_summary\r\n    WHERE metric_type = 'price_range'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "US Stock Most Volatile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  symbol AS metric,\r\n  metric_value AS value\r\nFROM us_stock_summary\r\nWHERE metric_type = 'price_range'\r\n  AND summary_time = (\r\n    SELECT MAX(summary_time)\r\n    FROM us_stock_summary\r\n    WHERE metric_type = 'price_range'\r\n  )\r\nORDER BY metric_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "BTC latest value",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  symbol AS metric,\r\n  avg_price AS value\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND symbol = 'BTCUSDT'\r\n  ORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "HOW MANY STOCK or CYPTO?",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  type,\r\n  count(DISTINCT symbol) AS \"assets count\"\r\nFROM realtime_prices\r\nWHERE type IN ('hk_stock', 'us_stock', 'crypto', 'index', 'war_oil') -- 🌟 淨係睇呢幾類\r\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Asia HK Stocks & Indices live",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  AND type IN ('hk_stock', 'index') -- 🌟 核心魔法：只允許港股和指數進入這張圖\r\nORDER BY window_start ASC;"
    }
   ]
  },
  {
   "title": "US_stock",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "dataset": "stock_db",
     "rawSql": "SELECT\r\n  window_start AS \"time\",\r\n  avg_price AS value,\r\n  symbol AS metric\r\nFROM realtime_prices\r\nWHERE $__timeFilter(window_start)\r\n  -- 🌟 核心魔法：只過濾美股同油股\r\n  AND type IN ('us_stock', 'war_oil') \r\nORDER BY window_start ASC;"
    }
   ]
  }
 ]
}